### ISSUE TITLE
Please add an option to disable the popup autoclosing :-)

### ISSUE THREAD

**Issue by sekmo** [billkeller/Delicious-Chrome-Extension#26]
Please add an option to disable the popup autoclosing :-)
I find it annoying when I see some good related links and a second later they disappear!

**Comment by sekmo** [comment]
Thanks!
It works flawlessly on mac os 10.8.5 :-)

**Comment by billkeller** [comment]
@sekmo It turns out that the Delicious save window does not auto-close if you're hovering over the related links. So I no longer force the window to close, and it's no longer an option on the options page. This update has been pushed out to the Google Chrome Web Store.
